# Generated by Django 5.0.1 on 2024-01-26 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 26, 19, 54, 26, 125417, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
