# Generated by Django 5.0.1 on 2024-02-08 21:48

import datetime
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
                ('objects', main.models.NewUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='orders',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 8, 21, 48, 16, 414360, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Админ?'),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_login',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Последняя дата входа'),
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.BooleanField(default=False, verbose_name='Модератор?'),
        ),
    ]
