# Generated by Django 5.0.1 on 2024-02-14 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_users_managers_alter_orders_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='order', verbose_name='Фото для обработки'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 14, 9, 44, 7, 829170, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
