# Generated by Django 5.0.1 on 2024-01-29 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_orders_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filters',
            options={'verbose_name': 'Фильтр', 'verbose_name_plural': 'Фильтры'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='filterorder',
            name='power',
            field=models.FloatField(default=0, verbose_name='Мощность'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 29, 15, 51, 2, 214884, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
