# Generated by Django 5.0.1 on 2024-01-29 15:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_filters_options_alter_orders_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filterorder',
            name='filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.filters'),
        ),
        migrations.AlterField(
            model_name='filterorder',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.orders'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 29, 15, 53, 35, 793842, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
